version: "2"
run:
  timeout: 5m
linters:
  enable:
    - govet
    - staticcheck
    - gosec
    - errcheck
    - ineffassign
    - unused
    - gocritic
    - modernize
  settings:
    govet:
      enable:
        - shadow
    staticcheck:
      checks:
        - all
        - -ST1000
        - -ST1003
        - -ST1016
    gosec:
      excludes:
        - G107
formatters:
  enable:
    - gofmt
    - goimports
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
